server:
  port: 9094
spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:bar}
      username: ${MONGODB_USER:Kharkiv_student}
      password: ${MONGODB_PASS:Glory_to_Ukraine}
      autoIndexCreation: true
uabrew:
  warehouse:
    host: ${UABREW_WAREHOUSE_HOST:localhost}
    port: ${UABREW_WAREHOUSE_PORT:9096}
    